baseURL: "/"
languageCode: "tb-poj"
title: "Hong-mô͘-sa Kang-chok-sek"

# Ī-siat gí-giân
defaultContentLanguage: "tb-poj"
defaultContentLanguageInSubdir: true      # Hián-sī ī-siat gí-giân ê phiau-thâu

# Siong-tùi URL (pī-bián localhost)
# Cloudflare Pages ài iōng absolute URL (absURL)
relativeURLs: false
canonifyURLs: true

# Sitemap siat-tēng
sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

privacy:
  googleAnalytics:
    anonymizeIP: true

# Kái-siān Hugo su-chhut
disableKinds:
  - taxonomy

# Asset koán-sòaⁿ
minify:
  enabled: true

enableInlineShortcodes: true
enableRobotsTXT: true
cleanDestinationDir: true     #Hugo tī build chìn-chêng chū-tōng chheng public
pagination:
  pagerSize: 10

params:
  custom_css:
    - "css/custom.css"

# CSS / JS settings (Tailwind)
assetDir: "assets"
staticDir: ["static"]

# PostCSS lō͘-kèng (Tailwind)
build:
  writeStats: false
  postCSS:
    use:
      - postcss
    includePaths:
      - "node_modules"

markup:
  goldmark:
    renderer:
      unsafe: true               # Enable HTML in Markdown (Blog)
  tableOfContents:
    startLevel: 2
    endLevel: 4