baseURL: "http://localhost:1313/"
languageCode: "tb-poj"
title: "芳芼莎工作室 HongMouSa Studio"
defaultContentLanguage: "tb-poj"
enableRobotsTXT: true
pagination.pagerSize: 10

params:
  custom_css:
    - "css/custom.css"

# CSS / JS settings (Tailwind)
assetDir: "assets"
staticDir: ["static"]

markup:
  goldmark:
    renderer:
      unsafe: true               # Enable HTML in Markdown (Blog)
  tableOfContents:
    startLevel: 2
    endLevel: 4

languages:
  tb-poj:
    languageName: "Tâi-bûn (Pe̍h-ōe-jī)"
    contentDir: "tb-poj"
    weight: 1
  tb-hj:
    languageName: "台文（漢字）"
    contentDir: "tb-hj"
    weight: 2
  en:
    languageName: "English"
    contentDir: "en"
    weight: 3

